import { SessionContext } from '@/context/SessionProvider'
import { api } from '@/services/api'
import axios from 'axios'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useContext, useEffect, useState } from 'react'
import { v4 as uuidv4 } from 'uuid'

export default function Home () {
  const { session } = useContext(SessionContext)
  const [admin, setAdmin] = useState(0)
  const router = useRouter()
  const [history, setHistory] = useState([])

  useEffect(() => {
    const data = ''

    const config = {
      method: 'get',
      maxBodyLength: Infinity,
      url: `${api.link}/history`,
      headers: { },
      data
    }

    axios.request(config)
      .then((response) => {
        console.log(JSON.stringify(response.data))
        setHistory(response.data)
      })
      .catch((error) => {
        console.log(error)
      })
  }, [])

  useEffect(() => {
    if (session) {
      if (session.admin === 1) {
        setAdmin(session.admin)
        return
      }
      router.push('/')
      return
    }
    router.push('/')
  }, [session])

  if (admin === 1) {
    return (
      <>
        <Head>
          <title>Consulta</title>
          <meta name='description' content='Generated by create next app' />
          <meta name='viewport' content='width=device-width, initial-scale=1' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <main className='flex flex-col items-center py-11 gap-24'>

          <div className='flex flex-col items-center gap-3 w-7/12'>
            {history && history.map((h) => <Reg h={h} key={uuidv4()} />)}
          </div>
        </main>
      </>
    )
  }
}

const Reg = ({ h }) => {
  return (
    <div className='flex gap-3 bg-[#fff] px-3 py-3 rounded-md'>
      <div className='flex flex-col shadow-md'>
        <span>{h.user.nombre}</span>
        <span>{h.user.correo}</span>
        <span>{h.user.telefono}</span>
        <span>{h.user.domicilio}</span>
      </div>
      <div className='flex flex-col shadow-md'>
        {h.productos.map((p) => {
          return (
            <span key={uuidv4()}>{p.nombre} ${p.precio}</span>
          )
        })}
      </div>
    </div>
  )
}
