import axios from 'axios'
import Head from 'next/head'
import { useState } from 'react'
import { api } from '@/services/api'
import { useRouter } from 'next/router'

export default function Home () {
  const [correo, setCorreo] = useState('')
  const [pw, setPw] = useState('')
  const [nombre, setNombre] = useState('')
  const [domicilio, setDomicilio] = useState('')
  const [telefono, setTelefono] = useState('')
  const [error, setError] = useState(false)
  const router = useRouter()

  const handleOnSubmit = (e) => {
    e.preventDefault()

    if (!correo || !pw || !nombre || !domicilio || !telefono) {
      setError(true)
      return
    }

    const data = JSON.stringify({
      correo,
      password: pw,
      admin: 0,
      nombre,
      domicilio,
      telefono
    })

    const config = {
      method: 'post',
      maxBodyLength: Infinity,
      url: `${api.link}/usuarios`,
      headers: {
        'Content-Type': 'application/json'
      },
      data
    }

    axios.request(config)
      .then(() => {
        router.push('/login')
      })
      .catch(() => { setError(true) })
  }

  return (
    <>
      <Head>
        <title>PcComponents - Create a user</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='flex flex-col items-center py-11 gap-24'>
        <form className='flex flex-col' onSubmit={handleOnSubmit}>
          <label>Correo</label>
          <input type='email' onChange={(e) => { setCorreo(e.target.value) }} />
          <label>Contraseña</label>
          <input type='password' onChange={(e) => { setPw(e.target.value) }} />
          <label>Nombre</label>
          <input type='text' onChange={(e) => { setNombre(e.target.value) }} />
          <label>Domicilio</label>
          <input type='text' onChange={(e) => { setDomicilio(e.target.value) }} />
          <label>Telefono</label>
          <input type='tel' onChange={(e) => { setTelefono(e.target.value) }} />
          <button type='submit'>Subir</button>
          {error && (
            <div>
              Ha ocurrido un error o ha faltado informacion
            </div>
          )}
        </form>
      </main>
    </>
  )
}
