import { SessionContext } from '@/context/SessionProvider'
import { api } from '@/services/api'
import axios from 'axios'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useContext, useEffect, useState } from 'react'

export default function Home () {
  const [nombre, setNombre] = useState('')
  const [desc, setDesc] = useState('')
  const [image, setImage] = useState()
  const [precio, setPrecio] = useState(0)
  const [err, setErr] = useState(false)
  const router = useRouter()
  const { session } = useContext(SessionContext)

  useEffect(() => {
    if (!session) {
      router.push('/')
      return
    }
    if (session.admin === 0) {
      router.push('/')
    }
  }, [session])

  const handleOnSubmit = (e) => {
    e.preventDefault()

    if (!nombre || !desc || !image || !precio) {
      setErr(true)
      return
    }

    const data = new FormData()

    data.append('file', image)

    const config = {
      method: 'post',
      maxBodyLength: Infinity,
      url: `${api.link}/upload`,
      data
    }

    axios.request(config)
      .then((response) => {
        const url = response.data.url

        const data = JSON.stringify({
          nombre,
          descripcion: desc,
          precio,
          imagen: url
        })

        const config = {
          method: 'post',
          maxBodyLength: Infinity,
          url: `${api.link}/producto`,
          headers: {
            'Content-Type': 'application/json'
          },
          data
        }

        axios.request(config)
          .then((response) => {
            router.push('/')
          })
          .catch((error) => {
            console.log(error)
            setErr(true)
          })
      })
      .catch(() => {
        setErr(true)
      })
  }

  if (session) {
    return (
      <>
        <Head>
          <title>PcComponents - Crear producto</title>
          <meta name='description' content='Generated by create next app' />
          <meta name='viewport' content='width=device-width, initial-scale=1' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <main className='flex flex-col items-center py-11 gap-24'>
          <form className='flex flex-col' onSubmit={handleOnSubmit}>
            <h1>
              Crear producto
            </h1>
            <label>Nombre</label>
            <input type='text' onChange={(e) => { setNombre(e.target.value) }} />
            <label>Descripcion</label>
            <input type='text' onChange={(e) => { setDesc(e.target.value) }} />
            <label>Precio</label>
            <input type='number' onChange={(e) => { setPrecio(e.target.value) }} />
            <label>Imagen</label>
            <input type='file' onChange={(e) => { setImage(e.target.files[0]) }} />
            <button type='submit' className='bg-violet-default text-[#fff] rounded-md py-1 px-3 m-auto'>
              Subir
            </button>
          </form>
          {err && (
            <>
              Ha ocurrido un error
            </>
          )}
        </main>
      </>
    )
  }
}
