import { Section } from '@/components/Section/Section'
import Head from 'next/head'

export default function Home () {
  return (
    <>
      <Head>
        <title>PcComponents</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='flex flex-col items-center py-11 gap-24'>
        <div>
          <span className='text-2xl font-semibold'>
            Productos
          </span>
        </div>
        <Section />
      </main>
    </>
  )
}
