import Head from 'next/head'
import Cookies from 'js-cookie'
import { useContext, useEffect, useState } from 'react'
import { SessionContext } from '@/context/SessionProvider'
import { useRouter } from 'next/router'
import axios from 'axios'
import { api } from '@/services/api'

export default function Home () {
  const [cart, setCart] = useState([])
  const { session } = useContext(SessionContext)
  const router = useRouter()

  useEffect(() => {
    const cart = Cookies.get('cart') ? JSON.parse(Cookies.get('cart')) : []
    setCart(cart)
    if (!session) {
      router.push('/login')
    }
  }, [])

  const handleOnSubmit = (e) => {
    e.preventDefault()
    const data = JSON.stringify({
      user: JSON.stringify(session),
      productos: JSON.stringify(cart)
    })

    const config = {
      method: 'post',
      maxBodyLength: Infinity,
      url: `${api.link}/reg/producto`,
      headers: {
        'Content-Type': 'application/json'
      },
      data
    }

    axios.request(config)
      .then((res) => {
        console.log(res.data)
        Cookies.remove('cart')
        router.push('/')
      })
      .catch((error) => {
        console.log(error)
      })
  }

  return (
    <>
      <Head>
        <title>Payload</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='flex flex-col items-center py-11 gap-5'>
        <form className='flex flex-col' onSubmit={handleOnSubmit}>
          <label>Metodo de pago</label>
          <select>
            <option>Debito</option>
            <option>Credito</option>
          </select>
          <button type='submit'>Realizar Pago</button>
        </form>
      </main>
    </>
  )
}
